services:
  react_test:
    build:
      context: .
      dockerfile: Dockerfile
    image: archilitav/react_test:latest
    container_name: react_test
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8098:8098"  
    command: sh -c "npm install && npm start"
    environment:
      - REACT_APP_ENV=development
