# services:
#   react_test:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: archilitav/react_test:latest
#     container_name: react_test
#     ports:
#       - "3001:3001"  
#     environment:
#       - REACT_APP_ENV=development
